apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: database
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb-standalone
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb-standalone
        image: mongo:4.0-xenial
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/k8-training/admin/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/k8-training/admin/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: k8-training
          mountPath: /etc/k8-training
          readOnly: true
      volumes:
      - name: k8-training
        secret:
          secretName: k8-training
          items:
          - key: MONGO_ROOT_USERNAME
            path: admin/MONGO_ROOT_USERNAME
            mode: 0444
          - key: MONGO_ROOT_PASSWORD
            path: admin/MONGO_ROOT_PASSWORD
            mode: 0444
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  clusterIP: None
  selector:
    app: database
